version: '3'
services:
  web:
    image: "tonyzhang1002/touch-fish:web"
    ports:
      - "8081:8080"
    networks:
      - touchfishnetwork
  db:
    image: "mongo:latest"
    networks:
      - touchfishnetwork
networks:
  touchfishnetwork:
    driver: bridge