version: '3'
services:
  web:
    image: "demo/touch-fish:0.0.1-SNAPSHOT"
    ports:
      - "8081:8080"
    networks:
      - nw
  db:
    image: "mongo:latest"
    networks:
      - nw
networks:
  nw:
    driver: bridge